image: mravenel/alpine

stages:
  - mirror
  - build
  
github-mirror:
  stage: mirror
  allow_failure: true
  script:
  - echo $CI_REPOSITORY_URL
  - apk --no-cache add git
  - cd /tmp
  - git clone --mirror $CI_REPOSITORY_URL
  - cd ci-sandbox.git
  - git push --mirror https://$GITHUB_TOKEN@github.com/mravenel/ci-sandbox.git

lolaus:
  stage: build
  script:
    - ./lolaus.sh README.md ls
  
