image: alpine

stages:
  - mirror
  
github-mirror:
  stage: mirror
  allow_failure: true
  script:
  - apk --no-cache add git
  - cd /tmp
  - git clone --mirror $CI_REPOSITORY_URL
  - cd ci-sandbox.git
  - git push --mirror https://$GITHUB_TOKEN@github.com/mravenel/ci-sandbox.git
  
